# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lyubaxapro/Computer-graphics/lab3/lab3_interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1585, 717)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cda = QtWidgets.QRadioButton(self.centralwidget)
        self.cda.setGeometry(QtCore.QRect(630, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cda.setFont(font)
        self.cda.setObjectName("cda")
        self.br_int = QtWidgets.QRadioButton(self.centralwidget)
        self.br_int.setGeometry(QtCore.QRect(630, 60, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.br_int.setFont(font)
        self.br_int.setObjectName("br_int")
        self.br_float = QtWidgets.QRadioButton(self.centralwidget)
        self.br_float.setGeometry(QtCore.QRect(630, 90, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.br_float.setFont(font)
        self.br_float.setObjectName("br_float")
        self.br_smoothing = QtWidgets.QRadioButton(self.centralwidget)
        self.br_smoothing.setGeometry(QtCore.QRect(630, 115, 420, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.br_smoothing.setFont(font)
        self.br_smoothing.setObjectName("br_smoothing")
        self.alg_vu = QtWidgets.QRadioButton(self.centralwidget)
        self.alg_vu.setGeometry(QtCore.QRect(630, 140, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alg_vu.setFont(font)
        self.alg_vu.setObjectName("alg_vu")
        self.draw_line_button = QtWidgets.QPushButton(self.centralwidget)
        self.draw_line_button.setGeometry(QtCore.QRect(630, 300, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.draw_line_button.setFont(font)
        self.draw_line_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.draw_line_button.setObjectName("draw_line_button")
        self.draw_bundle_button = QtWidgets.QPushButton(self.centralwidget)
        self.draw_bundle_button.setGeometry(QtCore.QRect(640, 470, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.draw_bundle_button.setFont(font)
        self.draw_bundle_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.draw_bundle_button.setObjectName("draw_bundle_button")
        self.x0_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.x0_entry.setGeometry(QtCore.QRect(710, 230, 61, 24))
        self.x0_entry.setMinimum(-290)
        self.x0_entry.setMaximum(290)
        self.x0_entry.setObjectName("x0_entry")
        self.y0_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.y0_entry.setGeometry(QtCore.QRect(780, 230, 61, 24))
        self.y0_entry.setMinimum(-290)
        self.y0_entry.setMaximum(290)
        self.y0_entry.setObjectName("y0_entry")
        self.standart = QtWidgets.QRadioButton(self.centralwidget)
        self.standart.setGeometry(QtCore.QRect(630, 170, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.standart.setFont(font)
        self.standart.setObjectName("standart")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 190, 351, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 230, 41, 21))
        self.label_3.setObjectName("label_3")
        self.xk_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.xk_entry.setGeometry(QtCore.QRect(710, 260, 61, 24))
        self.xk_entry.setMinimum(-290)
        self.xk_entry.setMaximum(290)
        self.xk_entry.setObjectName("xk_entry")
        self.yk_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.yk_entry.setGeometry(QtCore.QRect(780, 260, 61, 24))
        self.yk_entry.setMinimum(-290)
        self.yk_entry.setMaximum(290)
        self.yk_entry.setObjectName("yk_entry")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 260, 41, 24))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 340, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 380, 141, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(640, 420, 151, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.r_bundle_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.r_bundle_entry.setGeometry(QtCore.QRect(810, 380, 61, 31))
        self.r_bundle_entry.setMinimum(1)
        self.r_bundle_entry.setMaximum(290)
        self.r_bundle_entry.setSingleStep(1)
        self.r_bundle_entry.setObjectName("r_bundle_entry")
        self.angle_bundle_entry = QtWidgets.QSpinBox(self.centralwidget)
        self.angle_bundle_entry.setGeometry(QtCore.QRect(810, 420, 61, 31))
        self.angle_bundle_entry.setMinimum(-360)
        self.angle_bundle_entry.setMaximum(360)
        self.angle_bundle_entry.setObjectName("angle_bundle_entry")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(630, 340, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(620, 510, 281, 30))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.change_color_bg_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_color_bg_button.setGeometry(QtCore.QRect(630, 530, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.change_color_bg_button.setFont(font)
        self.change_color_bg_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_color_bg_button.setObjectName("change_color_bg_button")
        self.change_color_line_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_color_line_button.setGeometry(QtCore.QRect(630, 580, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.change_color_line_button.setFont(font)
        self.change_color_line_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_color_line_button.setObjectName("change_color_line_button")
        self.clear_canvas_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_canvas_button.setGeometry(QtCore.QRect(890, 300, 291, 43))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clear_canvas_button.setFont(font)
        self.clear_canvas_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_canvas_button.setObjectName("clear_canvas_button")
        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(-10, 0, 621, 621))
        self.canvas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canvas.setObjectName("canvas")
        self.bg_color_canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.bg_color_canvas.setGeometry(QtCore.QRect(850, 530, 101, 41))
        self.bg_color_canvas.setObjectName("bg_color_canvas")
        self.line_color_canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.line_color_canvas.setGeometry(QtCore.QRect(850, 580, 101, 41))
        self.line_color_canvas.setMinimumSize(QtCore.QSize(0, 0))
        self.line_color_canvas.setMaximumSize(QtCore.QSize(800, 505))
        self.line_color_canvas.setObjectName("line_color_canvas")
        self.time_serch_button = QtWidgets.QPushButton(self.centralwidget)
        self.time_serch_button.setGeometry(QtCore.QRect(10, 630, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_serch_button.setFont(font)
        self.time_serch_button.setObjectName("time_serch_button")
        self.stepping_search_button = QtWidgets.QPushButton(self.centralwidget)
        self.stepping_search_button.setGeometry(QtCore.QRect(330, 630, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stepping_search_button.setFont(font)
        self.stepping_search_button.setObjectName("stepping_search_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная №3"))
        self.cda.setText(_translate("MainWindow", "ЦДА"))
        self.br_int.setText(_translate("MainWindow", "Брезенхем(int)"))
        self.br_float.setText(_translate("MainWindow", "Брезенхем(float)"))
        self.br_smoothing.setText(_translate("MainWindow", "Брезенхем(устранение ступенчатости)"))
        self.alg_vu.setText(_translate("MainWindow", "Алгоритм Ву"))
        self.draw_line_button.setText(_translate("MainWindow", "Нарисовать линию"))
        self.draw_bundle_button.setText(_translate("MainWindow", "Нарисовать пучок"))
        self.standart.setText(_translate("MainWindow", "Библиотечный"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Выберите алгоритм:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Введите координаты линии:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">x</span><span style=\" font-size:14pt; vertical-align:sub;\">н </span><span style=\" font-size:14pt;\"> y</span><span style=\" font-size:14pt; vertical-align:sub;\">н</span><span style=\" font-size:14pt;\">:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">x</span><span style=\" font-size:14pt; vertical-align:sub;\">k</span><span style=\" font-size:14pt;\"> y</span><span style=\" font-size:14pt; vertical-align:sub;\">k</span><span style=\" font-size:14pt;\">:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Введите данные для пучка линий:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Радиус пучка:"))
        self.label_8.setText(_translate("MainWindow", "Шаг для угла:"))
        self.change_color_bg_button.setText(_translate("MainWindow", "Выбрать цвет фона"))
        self.change_color_line_button.setText(_translate("MainWindow", "Выбрать цвет линии"))
        self.clear_canvas_button.setText(_translate("MainWindow", "Очистить зону с рисуноком"))
        self.time_serch_button.setText(_translate("MainWindow", "Временные характеристики"))
        self.stepping_search_button.setText(_translate("MainWindow", "Исследование ступенчатости"))

